update generating keypair instructions, from sylabs 106
apptainer/apptainer-userdocs pull request #164
Opened 2023-02-16 10:18 UTC by edytuk

This pulls in sylabs PR
- sylabs/singularity-userdocs#106

The original PR description was:
> update documentation to support newer ssh-keygen versions for creating a new pem keypair.

2023-02-16 20:28 UTC, DrDaveD requested changes

2023-02-16 20:28 UTC, DrDaveD commented on encryption.rst
> +   $ ssh-keygen -t rsa -b 4096 -m pem -N ''
According to the man page and my testing, the `-m pem` option has no effect with that set of options, so please remove it.

2023-02-16 20:30 UTC, DrDaveD commented on encryption.rst
> +   $ ssh-keygen -t rsa -b 4096 -m pem -N ''
I changed my mind, it does make a difference on ubuntu

2023-02-16 20:31 UTC, DrDaveD approved these changes

2023-02-16 20:31 UTC, merged

2023-02-16 20:31 UTC, DrDaveD commented
Please also cherry-pick to 1.1 branch

2023-02-17 09:39 UTC, edytuk commented
1.1 branch already has these changes

2023-02-17 18:26 UTC, DrDaveD commented
Oh.  I didn't notice that this was for the 1.0 branch, I thought it was the main branch.  We didn't really have to backport this that far back, but I guess it doesn't hurt.