document templating (a.k.a. build-args) functionality, from sylabs199
apptainer/apptainer-userdocs pull request #250
Opened 2024-03-08 06:06 UTC by JasonYangShadow

This fixes a subpart of https://github.com/apptainer/apptainer-userdocs/issues/239 by merging

- https://github.com/sylabs/singularity-userdocs/pull/199
which fixed
- https://github.com/sylabs/singularity-userdocs/issues/190
The original PR description was:
> Adds a section to the definition_files.rst file, documenting the templating (a.k.a. "build args") functionality.

2024-03-08 14:47 UTC, DrDaveD requested changes
I see that you pretty much took their whole new section without making any changes to what you added in #199.  I think that is resulting in some redundancy, especially in the description of the %arguments section in definition_files.rst.  Please take another look, remove duplicate information and/or possibly have cross references between the sections.

2024-03-11 03:50 UTC, JasonYangShadow commented
> I see that you pretty much took their whole new section without making any changes to what you added in #199. I think that is resulting in some redundancy, especially in the description of the %arguments section in definition_files.rst. Please take another look, remove duplicate information and/or possibly have cross references between the sections.

thanks! I removed examples in the `arguments` section and created a reference.

2024-03-11 15:24 UTC, DrDaveD requested changes

2024-03-11 15:24 UTC, DrDaveD commented on definition_files.rst
> +.. _template arguments:
I don't see any other examples of references with spaces in them; please use an underscore instead.

2024-03-12 12:01 UTC, DrDaveD approved these changes

2024-03-12 12:01 UTC, merged