update DMTCP checkpoint demo code
apptainer/apptainer-userdocs pull request #300
Opened 2024-10-17 02:55 UTC by JasonYangShadow

## Description of the Pull Request (PR):

update DMTCP code to patch the demo. 

## This fixes or addresses the following GitHub issues:

- Fixes https://github.com/apptainer/apptainer/issues/2325

2024-10-17 03:09 UTC, JasonYangShadow commented
https://github.com/CrossNox/m2r2/issues/68
it looks like building docs fails due to the issue listed above.

2024-10-17 17:36 UTC, DrDaveD requested changes

2024-10-17 17:36 UTC, DrDaveD commented on checkpoint.rst
> +We can see that request count value is ``1`` when this application is started
Add `the` before `request`

2024-10-17 17:36 UTC, DrDaveD commented on checkpoint.rst
> +Now that request count variable on our server is in a new state, ``2``, we can use the
Again, `the` before `request

2024-10-17 17:36 UTC, DrDaveD commented on checkpoint.rst
> +meaning that previous request count value is ``2``.
Change `is` to `was` and either add `the` before `previous` or change `previous` to `previously the`.

2024-10-17 17:36 UTC, DrDaveD commented on checkpoint.rst
> +of the value of request count.
Add `the` before `previous`,`server`, and `request`

2024-10-17 17:36 UTC, DrDaveD commented on checkpoint.rst
> +Then access the application and see that request count value is restored as expected.
Add `the` before `request`

2024-10-17 17:58 UTC, DrDaveD commented
> [CrossNox/m2r2#68](https://github.com/CrossNox/m2r2/issues/68) it looks like building docs fails due to the issue listed above.

Can you fix it by installing a docutils version <0.21 in the github action?  It looks like it must currently be installing docutils as an implied dependency because it isn't explicitly listed.

2024-10-18 16:55 UTC, DrDaveD requested changes

2024-10-18 16:55 UTC, DrDaveD commented on .github/workflows/pull_request.yml
> +          pip install --user --upgrade --upgrade-strategy eager docutils==0.16 setuptools sphinx sphinx-rtd-theme restructuredtext_lint rstcheck pygments m2r2
Please add a comment here explaining why docutils version is selected and pointing to the m2r2 issue.

2024-10-21 16:53 UTC, DrDaveD approved these changes

2024-10-21 16:53 UTC, merged