Remove env vars refs
apptainer/apptainer-userdocs pull request #37
Opened 2022-01-27 03:43 UTC by pedroalvesbatista

## Description of the Pull Request (PR):

Updates references from SINGULARITY to APPTAINER.

## This fixes or addresses the following GitHub issues:

- Fixes #22

2022-01-27 17:55 UTC, DrDaveD requested changes
This seems to include too many commits, some not relevant to the referenced issue.

2022-01-27 22:30 UTC, ikaneshiro commented on appendix.rst
> +   (comma separated string) to bind to the ``/.apptainer.d/libs``
```suggestion
   (comma separated string) to bind to the ``/.singularity.d/libs``
```
This should remain the same

2022-01-27 22:30 UTC, ikaneshiro commented on appendix.rst
> +``/.apptainer.d/bootstrap_history``. {Singularity} will also alert you
```suggestion
``/.singularity.d/bootstrap_history``. {Singularity} will also alert you
```

2022-01-27 22:30 UTC, ikaneshiro commented on appendix.rst
> +   $ apptainer run docker-daemon:alpine:latest
Lets not change these command docs until we are doing a PR for #17

2022-01-27 22:30 UTC, ikaneshiro commented on appendix.rst
> +   $ apptainer run docker-archive:$(pwd)/alpine.tar
same here

2022-02-01 21:30 UTC, ikaneshiro approved these changes

2022-02-01 21:35 UTC, merged