Adds {orgrepo} to replace refs to github.com
apptainer/apptainer-userdocs pull request #51
Opened 2022-02-02 23:09 UTC by pedroalvesbatista

Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>

## Description of the Pull Request (PR):

Adds new {orgrepo} to replace refs to github.com.

## This fixes or addresses the following GitHub issues:

- Fixes #30

2022-02-03 15:22 UTC, DrDaveD commented
Actually, I'm sorry, I take it back: it's OK to use it in a github.com URL; there is only one place where it shouldn't be, and that's the first one listed in conf.py.

2022-02-03 17:30 UTC, DrDaveD requested changes
Besides the conflict, I still see a few additional github.com references to singularityware/singularity and sylabs/singularity that should be updated to use `{orgrepo}`.  

You might as well also change hpcng/singularity in the epub_identifier variable in conf.py to apptainer/apptainer at this time (I'm not sure if that could use `{orgrepo}`, I'm guessing not).

2022-02-11 22:24 UTC, pedroalvesbatista commented
There is also a example part in `gpu.rst` pointing to an example using Blender/OpenCL. Can we keep or look for some other way to reproduce this and put in out repo ?

2022-02-14 14:38 UTC, DrDaveD commented
> There is also a example part in `gpu.rst` pointing to an example using Blender/OpenCL. Can we keep or look for some other way to reproduce this and put in out repo ?

I'm not sure, but in any case it's not part of this issue.  I suggest creating a separate issue and we'll consider it later.

2022-02-14 14:43 UTC, DrDaveD requested changes

2022-02-14 14:43 UTC, DrDaveD commented on appendix.rst
> +<https://github.com/apptainer/apptainer/blob/master/examples/arch/>`_
These should be `{orgrepo}` instead of `apptainer/apptainer`.

2022-02-16 16:39 UTC, DrDaveD requested changes

2022-02-16 16:39 UTC, DrDaveD commented on contributing.rst
> +<https://github.com/apptainer-userdocs>`_.
These should be `{orgrepo}` instead of `apptainer`.

2022-02-16 19:45 UTC, DrDaveD commented
I'll finish this one too so it's done

2022-02-16 20:23 UTC, DrDaveD commented
Completed in #55

2022-02-16 20:23 UTC, closed without merging